services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - "25:25"
      - "5000:80"
    restart: unless-stopped

  dotnet-api:
    build:
      context: ./services/email
    container_name: dotnet-api
    ports:
      - "5058:5058"
    environment:
      ASPNETCORE_URLS: http://+:5058
      ConnectionStrings__MongoDbConnection: mongodb://mongo:27017
      ConnectionStrings__Database: PhishingDB
      EmailSettings__Host: smtp4dev
    depends_on:
      - mongo
      - smtp4dev

  nestjs:
    build:
      context: ./services/nest
    container_name: nestjs
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - dotnet-api
    environment:
      DB_IP: mongo
      DB_NAME: PhishingDB
      DB_PORT: "27017"
      EMAIL_API: http://dotnet-api:5058/api/email
      JWT_TOKEN: AMIRASDASDAS
      ALLOWED_ORIGINS: >-
        http://localhost:8080,http://localhost:3000,http://localhost:5173
    restart: unless-stopped

  website:
    build:
      context: ./ui/website
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0

volumes:
  mongo-data:
